services:
    mininet:
        build: .
        container_name: load-balancer-mininet
        volumes:
            - /lib/modules:/lib/modules
            - ./load_balancer:/load_balancer
        tty: true
        stdin_open: true
        network_mode: "bridge"
        privileged: true
