services:
  mininet:
    build: .
    container_name: mininet-pox
    privileged: true
    volumes:
      - .:/D58-FINAL-PROJECT
      - /lib/modules:/lib/modules
    tty: true
    stdin_open: true
    network_mode: "bridge"
